### ISSUE TITLE
ESP IOT network

### ISSUE THREAD

**Issue by mkeyno** [hallard/WebSocketToSerial#1]
hi @hallard  , and thanks for sharing the codes , sorry to make issue for my question , I was wondering if you could help me to my idea about IOT project, The idea is using async webserver on AP ESP module and other ESP station enabled sensor devices can send the data and receive the commands from server, the rate of data logging wont be rather than 1 request per second
what do you think about how strategy should I use ? sync or async
what header type? TCP or MQTT
I might add, the ESP AP server host the webpage , which is user can login and watch data or activities
also on net configuration when we intend to add new node to this net , how ESP client introduce itself to ESP AP server and send its information such as IP address, Number of sensor attached , type of sensor,...so after user can configure the sensor on the web page

**Comment by hallard** [comment]
Hi @mkeyno 
For Webserver on ESP8266 I strongly recommend to use Async, it's faster and have so much advantages that I think in near future it will be integrated as native.
To send Data, yes MQTT seems good, I don't use it, I'm doing request on Emoncms server directly without any problem.
ESP client depends on code you write, I don't have any ESP client to other, I have ESP Gateway with RF modules and client (ULPNode or any arduino) send data using RF (longer range, lower power) to Gateway.

**Comment by mkeyno** [comment]
thanks @hallard for your comments , I saw you fork the ESPeasy project , I was wondering what would be your idea to use this repo as core IOT projects, they trying to make home automation platform such as Domoticz project but , yet don't know how they make network of ESPs for Home automation project ,

**Comment by hallard** [comment]
@mkeyno I forked ESPeasy because I added support for SI7021 and TSL2501 sensors, just that, I'm not working on it anymore ;-)

**Comment by mkeyno** [comment]
can you advise me for create secure mesh network between ESP module (one master other slaves) what approach should I follow?

**Comment by mkeyno** [comment]
@hallard  I've tried to run your sketch on my esp and check its performance but I couldn't get any result , can you check the image and let me know what was wrong 
![serial esp link](https://cloud.githubusercontent.com/assets/6232001/18026954/a4185920-6c6b-11e6-9e2c-3c119167767c.jpg)

**Comment by hallard** [comment]
@mkeyno 
Seems all is working fine, until you are not connected to the device, only two commands are available,`help` and `connect` as indicated on the screen
So you need to type `connect` to connect to target first, then you'll be able to `heap`, `who` or whatever ;-)

**Comment by mkeyno** [comment]
did I miss somethings here? I thought when we type in either of serial console or in webpage side we can have it  in other side

**Comment by hallard** [comment]
@mkeyno 
that should works as you say, but send/receive should happen once you press "enter key", IE typing "hello world" on web socket should appears on serial as soon as you press enter on websocket terminal
