### ISSUE TITLE
ASyncWifiManager Support

### ISSUE THREAD

**Issue by ghost** [hallard/WebSocketToSerial#3]
Hi

https://github.com/alanswx/ESPAsyncWiFiManager should work with the ASyncWebserver on this project

Would be a great way of adding the configuration management (:

**Comment by hallard** [comment]
@openhardwarecoza 
Yes, thanks for the links, I already have somes also, but didn't have time to integrate into this small project, may be your is easier ;-)

**Comment by hallard** [comment]
@openhardwarecoza 
did you succeeded to add this feature ?
